name: Etapa2
on:
  push
    branches:
      - main 
jobs:
  build_ecr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA2YIB77CDIA5C527G 
        aws-secret-access-key:  ${{ secrets.SECRET_AWS }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: repo
      run: |
        docker build -t $ECR_REGISTRY/repo:latest .
        docker push $ECR_REGISTRY/repo:latest

